### ISSUE TITLE
SystemError: (libev) error creating signal/async pipe: No error

### ISSUE THREAD

**Issue by HelloZeroNet** [gilesbrown/gsqlite3#1]
Running demo.py on python 2.7.9/gevent 1.0.1

```
SystemError: (libev) error creating signal/async pipe: No error
Traceback (most recent call last):
  File "core.pyx", line 2044, in gevent.core._syserr_cb (gevent/gevent.core.c:34188)
  File "core.pyx", line 340, in gevent.core.loop._handle_syserr (gevent/gevent.core.c:6248)
  File "core.pyx", line 350, in gevent.core.loop.handle_error (gevent/gevent.core.c:6395)
  File "core.pyx", line 355, in gevent.core.loop._default_handle_error (gevent/gevent.core.c:6605)
  File "C:\Python27\lib\traceback.py", line 128, in print_exception
    _print(file, line, '')
  File "C:\Python27\lib\traceback.py", line 13, in _print
    file.write(str+terminator)
KeyboardInterrupt
(libev) error creating signal/async pipe: No error
```

**Comment by gilessbrown** [comment]
Hmm.  Don't know why I didn't get notified when you created this issue.  Anyway can you try out a later version of gevent?

**Comment by gilesbrown** [comment]
OK, no reply so I'm going to presume that this is no longer of interest.  I am 99% certain it is to do with behaviour in `gevent` and therefore out of my control so I'm closing this issue.

**Comment by HelloZeroNet** [comment]
Sorry for late reply: It's working with latest version of gevent, but not with 1.0.1 (as it defined in setup.py)

**Comment by gilesbrown** [comment]
Ah.  Thanks for letting me know.  It works for me with 1.0.1.  I think I may just remove the version bound from setup.py.

Get Outlook for Androidhttps://aka.ms/ghei36

On Tue, Sep 6, 2016 at 1:52 PM -0700, "ZeroNet" <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry for late reply: It's working with latest version of gevent, but not with 1.0.1 (as it defined in setup.py)

##
