### ISSUE TITLE
Python 3: AttributeError: type object 'sqlite3.Cursor' has no attribute 'next'

### ISSUE THREAD

**Issue by vsemionov** [gilesbrown/gsqlite3#8]
Very nicely written code. Unfortunately, on Python 3 (3.11 to be more specific) the following is raised when importing this module:
```python
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/victor/work/envs/picstylist-all/lib/python3.11/site-packages/gsqlite3.py", line 93, in <module>
    sqlite3.Cursor.next]:
    ^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'sqlite3.Cursor' has no attribute 'next'
```

**Comment by vsemionov** [comment]
Sorry, I didn't see it's fixed on master.
